### ISSUE TITLE
Cannot upload the same file twice

### ISSUE THREAD

**Issue by 5tigerjelly** [KSJI/alpha#10]
I uploaded the same file again and got this error on the console.
![image](https://user-images.githubusercontent.com/15973528/40897087-c2c32284-676d-11e8-804c-84732dd19f96.png)

```e {code_: "storage/unauthorized", message_: "Firebase Storage: User does not have permission to access 'images/tsne.png'.", serverResponse_: "{↵  "error": {↵    "code": 403,↵    "message": "Pe…n denied. Could not perform this operation"↵  }↵}", name_: "FirebaseError"}
code
:
(...)
code_
:
"storage/unauthorized"
message
:
(...)
message_
:
"Firebase Storage: User does not have permission to access 'images/tsne.png'."
name
:
(...)
name_
:
"FirebaseError"
serverResponse
:
(...)
serverResponse_
:
"{↵  "error": {↵    "code": 403,↵    "message": "Permission denied. Could not perform this operation"↵  }↵}"
__proto__
:
Object```

**Comment by Kyle-Simpson** [comment]
So we are not able to recreate this issue on our own machines, but experienced a similar bug in development where we would get a 403 error when we were not actually signed in and trying to upload a picture.  Since we are unable to recreate the issue and are also currently able to upload the same picture multiple times, we are going to label this as not a bug.

**Comment by abegel** [comment]
@5tigerjelly Can you confirm that this bug is gone?

**Comment by 5tigerjelly** [comment]
@abegel I created a new account. I was signed in. Uploaded two meals with the same image. 
I was able to upload but now 2nd image does not show up.

![image](https://user-images.githubusercontent.com/15973528/41080630-4e6a87e4-69dc-11e8-8519-2332419523c3.png)
