### ISSUE TITLE
Clicking cancel when trying to delete post causes undefined errors

### ISSUE THREAD

**Issue by JourneyToTheWes** [KSJI/alpha#12]
> Clicking cancel when deleting a post then pressing the back button takes me here: 
![image](https://user-images.githubusercontent.com/15175754/40898489-88d6c7b6-6776-11e8-8dcf-00199b943683.png)
> From here, pressing cancel again gives me this screen:
![image](https://user-images.githubusercontent.com/15175754/40898501-afb60e96-6776-11e8-9abf-48ec360f356e.png)

> If I pressed "Yes" when it asks if I'm sure I want to delete the post, It takes me back to the main page:
![image](https://user-images.githubusercontent.com/15175754/40898526-ed410950-6776-11e8-8ddc-f9fae6c6882e.png)

**Comment by JourneyToTheWes** [comment]
> Going back twice (from the first screen shot) takes me to this page with undefined values:
![image](https://user-images.githubusercontent.com/15175754/40898580-2ecaafa2-6777-11e8-993a-fd0e2c738d03.png)

**Comment by Kyle-Simpson** [comment]
This is not the expected functionality but is also not really a bug.  Due to the way props are passed through our application, a user must click on a post for the appropriate props to be passed to this page.  Because in this case you clicked the back arrow multiple times, the application does not know which set of props to display, and therefore cannot properly render the page you're returning to.  We will not be able to fix this within the 24 hour period.
