### ISSUE TITLE
Saving Profile with Empty Inputs Work

### ISSUE THREAD

**Issue by JourneyToTheWes** [KSJI/alpha#13]
![image](https://user-images.githubusercontent.com/15175754/40898682-cf933526-6777-11e8-9ec5-7b70b3d608d2.png)

**Comment by soobkwon** [comment]
When you do not re-enter and save any new values into your account settings, the values that are stored in the database will stay the same. I think you may have gotten confused since there is no feedback saying that the values are the same. This was also not a part of our design spec, so our devs in our group did overlook adding a message. However, because of the limited time to patch our group will not be able to implement this message as the amount of time it would take to research and fix may take too long.
