### ISSUE TITLE
Using Forgot Password to reset password still works even though wrong username is provided

### ISSUE THREAD

**Issue by janequichocho** [KSJI/alpha#15]
When resetting a forgotten password, you're asked to provide a username and email address. Even though I gave the wrong username for the correct email address, I was still able to reset my password.

Steps that caused error:
1. Create an account with the following information
     - Full Name: Bob Smith
     - Email: janequichocho97@gmail.com
     - Weight: 110 lbs
     - Username: Bob Smith
     - Password: password
2. Log out of account
3. Click on "Forgot Password"
4. Type in following information for the text fields
     - Username: bob_bob_bob
     - Email: janequichocho97@gmail.com
5. I received an email that allowed me to reset the password

**Comment by Kyle-Simpson** [comment]
This is an interesting design flaw where we anticipated asking for the username and email for a user to be able to reset a password, but it turned out that we just needed their email; so basically we included the Username input just to avoid breaking the requirements spec.  

More or less, this isn't a functionality bug as much as it is a poor initial design choice that ended up being non-influential.

**Comment by abegel** [comment]
@Kyle-Simpson This bug would also be interesting to discuss during your final presentation.
