### ISSUE TITLE
No Error Messages for Signup

### ISSUE THREAD

**Issue by cj-zhang** [KSJI/alpha#25]
<img width="1230" alt="screen shot 2018-06-04 at 5 32 55 pm" src="https://user-images.githubusercontent.com/32367995/40948458-6e28df6a-681d-11e8-8e8d-c6033668d63f.png">

No errors are given to the user when they submit faulty information, nor are they redirected anywhere.

**Comment by soobkwon** [comment]
This is technically not a bug because it was not a part of our design spec, and our devs in our group overlooked adding a message. Due to the limited 24 hours, our group will not be able to implement a solution as the amount of time it would take to research and fix may take too long. The user should also not be redirected anywhere else because they should stay on the signup page since they could not get passed our requirements.
