### ISSUE TITLE
User email change still allows old email to sign in

### ISSUE THREAD

**Issue by 5tigerjelly** [KSJI/alpha#9]
I create an account under `bmo5@uw.edu` 
I changed the account email to `bmo@uw.edu`.

I was still able to login to the old `bmo5@uw.edu` account and see the meal I inserted.

**Comment by Kyle-Simpson** [comment]
This is a bug we found a few days ago and were unable to solve without breaking our functionality (and still adhering to the requirements spec).  Our initial potential solution was to delete the old email from our Firebase database in order to prevent the user from logging in with the old email, but we were unable to achieve this functionality without removing the user from their instance (which would break the spec).  We decided that we wanted to prioritize the user experience over a user being able to log into a deprecated account, and will not be able to fix the issue in the 24 hour period.

**Comment by abegel** [comment]
@Kyle-Simpson Interesting bug. Maybe you could talk about this bug during your final project presentation.
